apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: production
type: Opaque
data:
  DB_NAME: d29yZHByZXNzCg==
  DB_USER: bWFjcm9zcwo=
  DB_PASS: MTIzNDU2Nzg5Cg==
  DB_HOST: ZGJtYWNyb3NzLmNkY29mcHp3bWRpYi51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb20K
