apiVersion: apps/v1
kind: Deployment
metadata:
  name: sosmed
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sosmed
      metadata: sosmed
  template:
    metadata:
      labels:
        name: sosmed
        metadata: sosmed
    spec:
      containers:
        - name: sosmed
          image: varidmahdi/sosmed:branch-appversion
          ports:
            - containerPort: 80
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: secretsosmed
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: secretsosmed
                  key: DB_PASS
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: secretsosmed
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: secretsosmed
                  key: DB_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: sosmed
  namespace: staging
spec:
  #type: LoadBalancer
  ports:
    - port: 80
      #nodePort: 30080
  selector:
    name: sosmed
---

