apiVersion: v1
kind: Secret
metadata:
  name: secretsosmed
  namespace: production
type: Opaque
data:
  DB_NAME: ZGJfc29zbWVk
  DB_USER: YWRtaW4=
  DB_PASS: cXdlcnR5dWlvcA==
  DB_HOST: ZGItYmlnLXByb2plY3QtY2lsc3kuY2Rjb2ZwendtZGliLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbQ==
