apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: staging
type: Opaque
data:
  DB_NAME: d29yZHByZXNz
  DB_USER: YWRtaW4=
  DB_PASS: cXdlcnR5dWlvcA==
  DB_HOST: ZGItYmlnLXByb2plY3QtY2lsc3kuY2Rjb2ZwendtZGliLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbQ==
